// Code generated by protoc-gen-go. DO NOT EDIT.
// source: getmeconfig.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	getmeconfig.proto

It has these top-level messages:
	GetConfigByNameRequest
	GetConfigsByTypeRequest
	GetConfigResponce
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigByNameRequest struct {
	ConfigName string `protobuf:"bytes,1,opt,name=ConfigName" json:"ConfigName,omitempty"`
	ConfigType string `protobuf:"bytes,2,opt,name=ConfigType" json:"ConfigType,omitempty"`
}

func (m *GetConfigByNameRequest) Reset()                    { *m = GetConfigByNameRequest{} }
func (m *GetConfigByNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigByNameRequest) ProtoMessage()               {}
func (*GetConfigByNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetConfigByNameRequest) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *GetConfigByNameRequest) GetConfigType() string {
	if m != nil {
		return m.ConfigType
	}
	return ""
}

type GetConfigsByTypeRequest struct {
	ConfigType string `protobuf:"bytes,1,opt,name=ConfigType" json:"ConfigType,omitempty"`
}

func (m *GetConfigsByTypeRequest) Reset()                    { *m = GetConfigsByTypeRequest{} }
func (m *GetConfigsByTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigsByTypeRequest) ProtoMessage()               {}
func (*GetConfigsByTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetConfigsByTypeRequest) GetConfigType() string {
	if m != nil {
		return m.ConfigType
	}
	return ""
}

type GetConfigResponce struct {
	Config []byte `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
}

func (m *GetConfigResponce) Reset()                    { *m = GetConfigResponce{} }
func (m *GetConfigResponce) String() string            { return proto.CompactTextString(m) }
func (*GetConfigResponce) ProtoMessage()               {}
func (*GetConfigResponce) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetConfigResponce) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*GetConfigByNameRequest)(nil), "api.GetConfigByNameRequest")
	proto.RegisterType((*GetConfigsByTypeRequest)(nil), "api.GetConfigsByTypeRequest")
	proto.RegisterType((*GetConfigResponce)(nil), "api.GetConfigResponce")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ConfigService service

type ConfigServiceClient interface {
	GetConfigByName(ctx context.Context, in *GetConfigByNameRequest, opts ...grpc.CallOption) (*GetConfigResponce, error)
	GetConfigsByType(ctx context.Context, in *GetConfigsByTypeRequest, opts ...grpc.CallOption) (ConfigService_GetConfigsByTypeClient, error)
}

type configServiceClient struct {
	cc *grpc.ClientConn
}

func NewConfigServiceClient(cc *grpc.ClientConn) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) GetConfigByName(ctx context.Context, in *GetConfigByNameRequest, opts ...grpc.CallOption) (*GetConfigResponce, error) {
	out := new(GetConfigResponce)
	err := grpc.Invoke(ctx, "/api.ConfigService/GetConfigByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetConfigsByType(ctx context.Context, in *GetConfigsByTypeRequest, opts ...grpc.CallOption) (ConfigService_GetConfigsByTypeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ConfigService_serviceDesc.Streams[0], c.cc, "/api.ConfigService/GetConfigsByType", opts...)
	if err != nil {
		return nil, err
	}
	x := &configServiceGetConfigsByTypeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigService_GetConfigsByTypeClient interface {
	Recv() (*GetConfigResponce, error)
	grpc.ClientStream
}

type configServiceGetConfigsByTypeClient struct {
	grpc.ClientStream
}

func (x *configServiceGetConfigsByTypeClient) Recv() (*GetConfigResponce, error) {
	m := new(GetConfigResponce)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ConfigService service

type ConfigServiceServer interface {
	GetConfigByName(context.Context, *GetConfigByNameRequest) (*GetConfigResponce, error)
	GetConfigsByType(*GetConfigsByTypeRequest, ConfigService_GetConfigsByTypeServer) error
}

func RegisterConfigServiceServer(s *grpc.Server, srv ConfigServiceServer) {
	s.RegisterService(&_ConfigService_serviceDesc, srv)
}

func _ConfigService_GetConfigByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetConfigByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ConfigService/GetConfigByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetConfigByName(ctx, req.(*GetConfigByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetConfigsByType_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetConfigsByTypeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigServiceServer).GetConfigsByType(m, &configServiceGetConfigsByTypeServer{stream})
}

type ConfigService_GetConfigsByTypeServer interface {
	Send(*GetConfigResponce) error
	grpc.ServerStream
}

type configServiceGetConfigsByTypeServer struct {
	grpc.ServerStream
}

func (x *configServiceGetConfigsByTypeServer) Send(m *GetConfigResponce) error {
	return x.ServerStream.SendMsg(m)
}

var _ConfigService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigByName",
			Handler:    _ConfigService_GetConfigByName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConfigsByType",
			Handler:       _ConfigService_GetConfigsByType_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "getmeconfig.proto",
}

func init() { proto.RegisterFile("getmeconfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0x2d, 0xc9,
	0x4d, 0x4d, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x2c, 0xc8, 0x54, 0x8a, 0xe0, 0x12, 0x73, 0x4f, 0x2d, 0x71, 0x06, 0x8b, 0x3b, 0x55, 0xfa, 0x25,
	0xe6, 0xa6, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0x41, 0x84, 0x41,
	0x82, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x08, 0xf9, 0x90, 0xca, 0x82, 0x54,
	0x09, 0x26, 0x64, 0x79, 0x90, 0x88, 0x92, 0x25, 0x97, 0x38, 0xdc, 0xe4, 0x62, 0xa7, 0x4a, 0x90,
	0x18, 0x86, 0xd1, 0x60, 0xad, 0x8c, 0x18, 0x5a, 0xb5, 0xb9, 0x04, 0xe1, 0x5a, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x92, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x20, 0x22, 0x60, 0x0d, 0x3c, 0x41, 0x50,
	0x9e, 0xd1, 0x62, 0x46, 0x2e, 0x5e, 0x08, 0x33, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x8d, 0x8b, 0x1f, 0xcd, 0x4f, 0x42, 0xd2, 0x7a, 0x89, 0x05, 0x99, 0x7a, 0xd8, 0x7d, 0x2a, 0x25,
	0x86, 0x2a, 0x09, 0xb7, 0xd1, 0x8b, 0x4b, 0x00, 0xdd, 0x07, 0x42, 0x32, 0xa8, 0x6a, 0x51, 0x3d,
	0x86, 0xcb, 0x24, 0x03, 0xc6, 0x24, 0x36, 0x70, 0x98, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xee, 0xd0, 0xf3, 0xd8, 0x88, 0x01, 0x00, 0x00,
}
