// Code generated by protoc-gen-go. DO NOT EDIT.
// source: getmeconfig.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	getmeconfig.proto

It has these top-level messages:
	GetConfigByNameRequest
	GetConfigsByTypeRequest
	GetConfigResponce
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetConfigByNameRequest struct {
	ConfigName string `protobuf:"bytes,1,opt,name=ConfigName" json:"ConfigName,omitempty"`
	ConfigType string `protobuf:"bytes,2,opt,name=ConfigType" json:"ConfigType,omitempty"`
}

func (m *GetConfigByNameRequest) Reset()                    { *m = GetConfigByNameRequest{} }
func (m *GetConfigByNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigByNameRequest) ProtoMessage()               {}
func (*GetConfigByNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetConfigByNameRequest) GetConfigName() string {
	if m != nil {
		return m.ConfigName
	}
	return ""
}

func (m *GetConfigByNameRequest) GetConfigType() string {
	if m != nil {
		return m.ConfigType
	}
	return ""
}

type GetConfigsByTypeRequest struct {
	ConfigType string `protobuf:"bytes,1,opt,name=ConfigType" json:"ConfigType,omitempty"`
}

func (m *GetConfigsByTypeRequest) Reset()                    { *m = GetConfigsByTypeRequest{} }
func (m *GetConfigsByTypeRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigsByTypeRequest) ProtoMessage()               {}
func (*GetConfigsByTypeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetConfigsByTypeRequest) GetConfigType() string {
	if m != nil {
		return m.ConfigType
	}
	return ""
}

type GetConfigResponce struct {
	Config []byte `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
}

func (m *GetConfigResponce) Reset()                    { *m = GetConfigResponce{} }
func (m *GetConfigResponce) String() string            { return proto.CompactTextString(m) }
func (*GetConfigResponce) ProtoMessage()               {}
func (*GetConfigResponce) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetConfigResponce) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*GetConfigByNameRequest)(nil), "api.GetConfigByNameRequest")
	proto.RegisterType((*GetConfigsByTypeRequest)(nil), "api.GetConfigsByTypeRequest")
	proto.RegisterType((*GetConfigResponce)(nil), "api.GetConfigResponce")
}

func init() { proto.RegisterFile("getmeconfig.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4f, 0x2d, 0xc9,
	0x4d, 0x4d, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x2c, 0xc8, 0x54, 0x8a, 0xe0, 0x12, 0x73, 0x4f, 0x2d, 0x71, 0x06, 0x8b, 0x3b, 0x55, 0xfa, 0x25,
	0xe6, 0xa6, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0x41, 0x84, 0x41,
	0x82, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x08, 0xf9, 0x90, 0xca, 0x82, 0x54,
	0x09, 0x26, 0x64, 0x79, 0x90, 0x88, 0x92, 0x25, 0x97, 0x38, 0xdc, 0xe4, 0x62, 0xa7, 0x4a, 0x90,
	0x18, 0x86, 0xd1, 0x60, 0xad, 0x8c, 0x18, 0x5a, 0xb5, 0xb9, 0x04, 0xe1, 0x5a, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x92, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x20, 0x22, 0x60, 0x0d, 0x3c, 0x41, 0x50,
	0x9e, 0xd1, 0x62, 0x46, 0x2e, 0x5e, 0x08, 0x33, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8,
	0x8d, 0x8b, 0x1f, 0xcd, 0x4f, 0x42, 0xd2, 0x7a, 0x89, 0x05, 0x99, 0x7a, 0xd8, 0x7d, 0x2a, 0x25,
	0x86, 0x2a, 0x09, 0xb7, 0xd1, 0x8b, 0x4b, 0x00, 0xdd, 0x07, 0x42, 0x32, 0xa8, 0x6a, 0x51, 0x3d,
	0x86, 0xcb, 0x24, 0x03, 0xc6, 0x24, 0x36, 0x70, 0x98, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xee, 0xd0, 0xf3, 0xd8, 0x88, 0x01, 0x00, 0x00,
}
